name: Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.4
          arcitecture: x64
      - name: Chachout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        uses: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'test'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
